[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Force PlatformIO to use your exact CH340 serial port
upload_port = /dev/cu.usbserial-2110
monitor_port = /dev/cu.usbserial-2110

; Auto-regenerate IntelliSense data on every build
build_flags =
